[package]
name = "tmplr"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlebars = "4.3.7"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.21"
clap = "2.33.3"
clap_derive = "3.0.0"
